### ISSUE TITLE
compilation error due to definition of integer types in LAPACK on armv7 iOS

### ISSUE THREAD

**Issue by dastrobu** [dastrobu/NdArray#10]
@EliaCereda I saw you deleted Matrix.swift in you fork. So I expect there are some issues with the matrix type for you. Would appreciate it if you could share them.

**Comment by EliaCereda** [comment]
I was having compilation errors on iOS with Xcode 11.3, a mismatch between Int and Int32 in some places if I recall correctly. I just removed since I didn’t need it at the moment and didn’t have a chance to look back into it.

I can send you the details in a couple of days when I’m back at the computer.

A couple more issues I wanted to share with you (leaving this here so I don’t forget): 
* There is a lot of overhead in allocating and deallocating ArraySlice, it was the most expensive part in a loop that I wrote. Maybe implementing it as a struct would have better performance?
* Subscript of ArraySlice expects an ArraySlice, so I couldn’t set it with an Array. I had to use copyTo to make it work.

**Comment by EliaCereda** [comment]
I managed to narrow down the compilation error to the definition of integer types in LAPACK on armv7 iOS, arm64 appears to be compiling correctly.

```
/.../NdArray/Sources/NdArray/Matrix.swift:180:17: error: cannot convert value of type 'Int32' to expected argument type '__CLPK_integer' (aka 'Int')
        dgesv_(&n, &nrhs, A.data, &lda, &ipiv, B.data, &ldb, &info)
                ^
                __CLPK_integer( )
/.../NdArray/Sources/NdArray/Matrix.swift:215:18: error: cannot convert value of type 'Int32' to expected argument type '__CLPK_integer' (aka 'Int')
        dgetri_(&n, A.data, &lda, &ipiv, &work, &lwork, &info)
                 ^
                 __CLPK_integer( )
/.../NdArray/Sources/NdArray/Matrix.swift:225:18: error: cannot convert value of type 'Int32' to expected argument type '__CLPK_integer' (aka 'Int')
        dgetri_(&n, A.data, &lda, &ipiv, &work, &lwork, &info)
                 ^
                 __CLPK_integer( )
/.../NdArray/Sources/NdArray/Matrix.swift:260:18: error: cannot convert value of type 'Int32' to expected argument type '__CLPK_integer' (aka 'Int')
        dgetrf_(&m, &n, data, &lda, &ipiv, &info)
                 ^
                 __CLPK_integer( )
/.../NdArray/Sources/NdArray/Matrix.swift:339:17: error: cannot convert value of type 'Int32' to expected argument type '__CLPK_integer' (aka 'Int')
        sgesv_(&n, &nrhs, A.data, &lda, &ipiv, B.data, &ldb, &info)
                ^
                __CLPK_integer( )
/.../NdArray/Sources/NdArray/Matrix.swift:374:18: error: cannot convert value of type 'Int32' to expected argument type '__CLPK_integer' (aka 'Int')
        sgetri_(&n, A.data, &lda, &ipiv, &work, &lwork, &info)
                 ^
                 __CLPK_integer( )
/.../NdArray/Sources/NdArray/Matrix.swift:384:18: error: cannot convert value of type 'Int32' to expected argument type '__CLPK_integer' (aka 'Int')
        sgetri_(&n, A.data, &lda, &ipiv, &work, &lwork, &info)
                 ^
                 __CLPK_integer( )
/.../NdArray/Sources/NdArray/Matrix.swift:419:18: error: cannot convert value of type 'Int32' to expected argument type '__CLPK_integer' (aka 'Int')
        sgetrf_(&m, &n, data, &lda, &ipiv, &info)
                 ^
                 __CLPK_integer( )
```

**Comment by dastrobu** [comment]
@EliaCereda the compilation error should be fixed in the linked PR. Thanks for bringing this up. I would appreciate creating separate issues for the two points you mentioned: 

> There is a lot of overhead in allocating and deallocating ArraySlice, it was the most expensive part in a loop that I wrote. Maybe implementing it as a struct would have better performance?

> Subscript of ArraySlice expects an ArraySlice, so I couldn’t set it with an Array. I had to use copyTo to make it work.

Ideally with small examples of your use cases.
