### ISSUE TITLE
Float Matrix Vector Multiplication

### ISSUE THREAD

**Issue by khirotaka** [dastrobu/NdArray#17]
Hello! I started using this library from your comment on Untouched Wilderness (Swift Numerics).
This library is really really great!!!

I have a question. when I ran the following code with reference to the README,

```swift
import NdArray
let A = Matrix<Float>.ones([2, 2])
let x = Vector<Float>.ones(2)
print(A * x)
```
I got the following error.
```
 BLAS error: Parameter number 7 passed to cblas_sgemv had an invalid value
Program ended with exit code: 255
```

Does this library currently not support operations other than Double?

For your information, my execution environment is as follows
- macOS Big Sur v11.1
- Apple M1
- Swift v5.3.2

Thanks !

**Comment by dastrobu** [comment]
@khirotaka thanks for the positive feedback. I think you simply found a bug here. Everything that works for doubles should also work for floats. Should be fixed soon.
